### ISSUE TITLE
compare with proteus (info)

### ISSUE THREAD

**Issue by joinr** [xadecimal/mutable-var#1]
https://github.com/ztellman/proteus

curious how the 1-entry array approach compares with having a primitive mutable object field.

**Comment by joinr** [comment]
rough benching (just incrementing a primitive number) looks equivalent.

**Comment by didibus** [comment]
I had looked at Proteus, but now I can't remember why I didn't use it and wrote my own. It was the inspiration for this lib though. I wrote the lib over a year ago, and was just sitting on it, so decided to publish it just now.

I think one reason was the interface of Proteus mimics "let", and I wanted something more like Java.

I do know Proteus being archived maybe was one reason. I also figured arrays would be more efficient since Proteus needs to instantiate an object for each variable. And then I think I thought arrays might have the JVM be able to use escape analysis to move them on the stack.

I think I started with a similar to Proteus approach, might have even forked Proteus at first, but as I was changing it to have the interface I wanted, I also realized you don't even need a wrapping class, and can just use arrays directly.

**Comment by didibus** [comment]
One difference is Proteus only supports Object, boolean, long and double types: https://github.com/ztellman/proteus/blob/master/src/proteus/Containers.java but mutable-var supports all primitive types: boolean, byte, char, short, int, long, float, double and Object.
